name: macOS

on:
  push:
    tags:
    - '*'

jobs:
  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          nbxc_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/v||')
          release_name="nbxc-desktop-macOS-v$nbxc_ver"
          app_name="NIBBLE-GUI.app"
          lang_folder="/Contents/Resources/languages"
          brew install gcc boost@1.60
          brew link boost@1.60 --force
          rm -rf cryptonote
          git clone https://github.com/Sudosups/Nibble cryptonote
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -DCMAKE_C_FLAGS="-mmacosx-version-min=10.12" -DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.12" -D CMAKE_BUILD_TYPE=Release ../..
          make
          mkdir "$app_name$lang_folder"
          cp ../../src/languages/*.qm "$app_name$lang_folder"
          macdeployqt "$app_name"
          cpack
          mv *.dmg "$release_name".dmg
          sha256=$(shasum -a 256 "$release_name".dmg | awk '{ print toupper($1) }')
          asset_path="./$build_folder/$release_name.dmg"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=nbxc_ver::${nbxc_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Nibble Desktop v${{ steps.build.outputs.nbxc_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
