name: Ubuntu 18.04

on:
  push:
    tags:
    - '*'

jobs:
  build-ubuntu16:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          BOOST_ROOT=
          sudo apt update -y
          sudo apt install -y qt5-default libboost-all-dev
          build_folder="build/release"
          nbxc_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/v||')
          release_name=nbxc-desktop-ubuntu-18.04-v"$nbxc_ver"
          app_name="NIBBLE-GUI"
          rm -rf cryptonote
          git clone https://github.com/Nibble-Network/Nibble.git cryptonote
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../..
          make
          tar -czf "$release_name".tar.gz "$app_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name".tar.gz
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=nbxc_ver::${nbxc_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Nibble Desktop v${{ steps.build.outputs.nbxc_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
